# Generated by Django 3.0.3 on 2020-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('exp', models.CharField(max_length=8)),
                ('count', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=100)),
            ],
        ),
    ]
