# Generated by Django 3.0.3 on 2020-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='exp',
            field=models.CharField(max_length=10),
        ),
    ]
