# Generated by Django 3.0.3 on 2020-04-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200408_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='food',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='main_app.Food'),
        ),
    ]
