# Generated by Django 3.0.3 on 2020-04-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comments_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.Food'),
        ),
    ]
