# Generated by Django 3.0.3 on 2020-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_food_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('T', 'Toronto'), ('M', 'Mississauga'), ('B', 'Brampton'), ('V', 'Vaughan'), ('W', 'Waterloo'), ('S', 'Scarborough'), ('N', 'North York'), ('E', 'Etobicoke'), ('O', 'Oakville')], max_length=1)),
                ('category', models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('S', 'Shoes'), ('T', 'Technology')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(related_name='food', to='main_app.Category'),
        ),
    ]
