# Generated by Django 3.0.3 on 2020-04-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200413_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('S', 'Shoes'), ('T', 'Technology'), ('F', 'Furniture')], max_length=1),
        ),
    ]
