# Generated by Django 3.0.3 on 2020-04-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200414_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='location',
            new_name='city',
        ),
    ]
